sudo: required
services:
  - docker

# Crear variables de entorno.
# If we defined a single environment variable name with different values, we can run them in paralel afterwards.
env:
  - NPM_TARGET=test
  - NPM_TARGET=lint
  - NPM_TARGET=coverage

before_install:
  - docker pull node:8-onbuild #docker Base image with Node.js

install:
  - docker build -t probot-hello . # Dot references the current working dir
  # -t is for 'tag', which means that our image will be called 'probot-hello'

script:
  - docker run --rm probot-hello npm run $NPM_TARGET # Will be substituted by the env values of the variable.

#after_success is use to run scripts only if the build was successful. We'll create a docker image with a tag that represents the name of the image plus the commit ID of the changes. This will be created only if $NPM_TARGET is equal to 'test'
# set -x -v; can expose secrets!
after_success:
  - set -x -v;
    set -e;
    if [ "${NPM_TARGET}" = "test" ]; then
      docker tag probot-hello probot-hello:$(git rev-parse HEAD);
    else
      echo "skipping docker tag";
    fi;
    docker images;
    set +x +v;
