sudo: required
services:
  - docker

## Create Environment Variables.
## If we defined a single environment variable name with different values, we can run them in paralel afterwards.
## The value of the NODE_VERSION comes from hub.docker.com, in the offcial node image repo.
env:
  - NODE_VERSION=8-jessie
  - NODE_VERSION=10-jessie

# # We are now building the DOCKER IMAGE on the script Phase
script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t node:$NODE_VERSION --build-arg NODE_IMAGE="node:${NODE_VERSION}" .
  - docker images
  - docker tag node:$NODE_VERSION $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) # We had to create this repo manually in hub.docker first (dawidh15/probot-hello)
  - docker push node:$NODE_VERSION $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) #publish image
  - docker run --rm probot-hello npm run $NPM_TARGET # Will be substituted by the env values of the variable.

# Stage treats everything under script as an action called "test"
stage:
  - test
  - npm-targets

jobs:
  include:
    - stage: npm-targets
      name: "Test 8-jessie"
      install: skip
      script:
      - docker run --rm node:$NODE_VERSION $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET #This runs the image we've created under script above "stage" tag
      env:
      - NODE_VERSION=8-jessie
      - NPM_TARGET=test
    - stage: npm-targets
      name: "Lint 8-jessie"
      install: skip
      script:
      - docker run --rm node:$NODE_VERSION $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET #This runs the image we've created under script above "stage" tag
      env:
      - NODE_VERSION=8-jessie
      - NPM_TARGET=lint
      - stage: npm-targets
        name: "Test 10-jessie"
        install: skip
        script:
        - docker run --rm node:$NODE_VERSION $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET #This runs the image we've created under script above "stage" tag
        env:
        - NODE_VERSION=10-jessie
        - NPM_TARGET=test
      - stage: npm-targets
        name: "Lint 10-jessie"
        install: skip
        script:
        - docker run --rm node:$NODE_VERSION $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD) npm run $NPM_TARGET #This runs the image we've created under script above "stage" tag
        if: branch = master
        env:
        - NODE_VERSION=10-jessie
        - NPM_TARGET=lint
